default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: statisfy_dev
  pool: 5
  host: localhost
  username: baldor
  password: baldor123

production:
  adapter: postgresql
  encoding: utf8
  database: statisfy_prod
  pool: 5
  host: localhost
  username: baldor
  password: baldor123

test:
  adapter: postgresql
  encoding: utf8
  database: statisfy_test
  pool: 5
  host: localhost
  username: baldor
  password: baldor123
